---
services:
  adoagent:
    image: rdp870/ado-agent:latest
    container_name: ado-agent
    labels:
      - namespace=monitor
    restart: unless-stopped
    environment:
      AZP_AGENT_NAME: "Docker Agent - Linux"
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: '2048M'
        reservations:
          memory: '256M'