---
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    network_mode: host
    volumes:
      - plex_data:/config
      - /mnt/plexmedia:/data
    environment:
      - TZ=${timezone}
      - PLEX_CLAIM=${claim_token}
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1024M'
        reservations:
          memory: '256M'

volumes:
  plex_data: