version: '3'
services:
  adguardhome:
    image: adguard/adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/lib/docker/volumes/adguard-conf/_data:/opt/adguardhome/conf
      - /var/lib/docker/volumes/adguard-work/_data:/opt/adguardhome/work
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8008:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 853:853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 6060:6060/tcp
    deploy:
      resources:
        limits:
          cpus: '1.00' # Limit to 50% of a single CPU
          memory: '1024M' # Limit max RAM to 512MB
        reservations:
          memory: '256M' # Reserve 256MB of RAM